export function trendCanBeZero(key: string): boolean {
  switch (key) {
    case 'timeAboveLimit':
      return true;
    case 'averageSaturationPercentage':
      return false;
    case 'vO2Max':
      return false;
    case 'recoveryScore':
      return false;
    case 'activityScore':
      return false;
    case 'sleepScore':
      return false;
    case 'swimmingNumberOfStrokes':
      return true;
    case 'swimmingNumberOfLaps':
      return true;
    case 'swimmingPoolLengthMeters':
      return true;
    case 'floorsClimbed':
      return true;
    case 'elevationLossMeters':
      return true;
    case 'minimumElevationMeters':
      return true;
    case 'averageElevationMeters':
      return true;
    case 'elevationGainMeters':
      return true;
    case 'maximumElevationMeters':
      return true;
    case 'elevationGainPlannedMeters':
      return true;
    case 'steps':
      return true;
    case 'distance':
      return true;
    case 'lowIntensityTime':
      return true;
    case 'highIntensityTime':
      return true;
    case 'inactiveTime':
      return true;
    case 'moderateIntensityTime':
      return true;
    case 'averageActivityLevel':
      return false;
    case 'calories':
      return true;
    case 'maximumHeartRate':
      return false;
    case 'minimumHeartRate':
      return false;
    case 'restingHeartRate':
      return false;
    case 'averageHeartRate':
      return false;
    case 'averageHrv':
      return false;
    case 'timeActive':
      return true;
    case 'timeResting':
      return true;
    case 'amountOfLowIntensityWork':
      return true;
    case 'amountOfVigorousIntensityWork':
      return true;
    case 'numberOfContinuousInactivePeriods':
      return true;
    case 'totalTimeInactive':
      return true;
    case 'totalModerateIntensityTime':
      return true;
    case 'timeSpentStanding':
      return true;
    case 'timeInBed':
      return false;
    case 'undeterminedSleepStageTime':
      return true;
    case 'sleepEfficiency':
      return true;
    case 'totalShortInterruptedTime':
      return true;
    case 'timeAwake':
      return false;
    case 'totalLongInterruptedTime':
      return true;
    case 'numberOfTimesAwareInTheNight':
      return true;
    case 'timeInLightSleep':
      return false;
    case 'timeAsleep':
      return false;
    case 'numberOfREMEvents':
      return true;
    case 'timeInDeepSleep':
      return false;
    case 'temperature':
      return true;
    case 'readinessScore':
      return false;
    case 'minimumBreathsPerMinute':
      return false;
    case 'averageBreathsPerMinute':
      return false;
    case 'maximumBreathsPerMinute':
      return false;
    case 'numberOfSnoringEvents':
      return true;
    case 'totalTimeSnoring':
      return true;
    default:
      throw new Error(`Unknown key: ${key}`) as never;
  }
}
