import { start } from "./api";
import type {
  AuthResponse,
  LoginResponse,
  RegisterResponse,
  TargetResponse,
  SearchResponse,
  Activity,
  Medication,
  Symptom,
  SymptomCategory,
  CreateResponse,
  GetResponse,
  PatchResponse,
  PostResponse,
  DeleteResponse,
  TrendsResponse,
  SymptomTrendsResponse,
  // websockets
  WebsocketMessage,
  WebsocketMessageType,
  WSDisconnect,
  WSError,
  WSInit,
  WSMessage,
  WSPing,
  AssistantSocketStream,
  ActiveClients,
} from "./types";

start();

export {
  AuthResponse,
  LoginResponse,
  RegisterResponse,
  TargetResponse,
  SearchResponse,
  Activity,
  Medication,
  Symptom,
  SymptomCategory,
  CreateResponse,
  GetResponse,
  PatchResponse,
  DeleteResponse,
  PostResponse,
  TrendsResponse,
  SymptomTrendsResponse,
  // websockets
  WebsocketMessage,
  WebsocketMessageType,
  WSDisconnect,
  WSError,
  WSInit,
  WSMessage,
  WSPing,
  AssistantSocketStream,
  ActiveClients,
};
